#!/bin/bash
# set -e

# script to initialize vibra_pricing
conda activate vibra_pricing
python -c 'import gamma.config' || make install-deps

HERE="$(dirname $(readlink -f $0))"
#export PYTHONPATH="$HERE"
#export GAMMA_CONFIG_ROOT="$HERE/config"
export PYTHONPATH="$PWD"
export GAMMA_CONFIG_ROOT="$PWD/config"
